export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#d9dadd",
        "on-primary-container": "#502600",
        "tertiary-fixed-dim": "#61de8a",
        "on-tertiary-fixed-variant": "#005228",
        "on-tertiary-container": "#003a1a",
        "tertiary-container": "#29af61",
        "outline": "#897365",
        "primary-container": "#e67e22",
        "tertiary-fixed": "#7efba4",
        "on-secondary-fixed-variant": "#45455b",
        "background": "#f8f9fc",
        "secondary-container": "#e2e0fc",
        "secondary-fixed-dim": "#c6c4df",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "outline-variant": "#dcc1b1",
        "surface-container": "#edeef1",
        "secondary": "#5d5c74",
        "surface-container-high": "#e7e8eb",
        "surface-container-low": "#f2f3f6",
        "secondary-fixed": "#e2e0fc",
        "primary-fixed": "#ffdcc5",
        "primary-fixed-dim": "#ffb783",
        "surface-variant": "#e1e2e5",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3133",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "surface-tint": "#944a00",
        "surface": "#f8f9fc",
        "on-primary-fixed-variant": "#713700",
        "on-surface-variant": "#564337",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#00210c",
        "on-primary-fixed": "#301400",
        "tertiary": "#006d37",
        "on-secondary-container": "#63627a",
        "inverse-primary": "#ffb783",
        "surface-container-highest": "#e1e2e5",
        "primary": "#944a00",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1a1a2e",
        "surface-bright": "#f8f9fc",
        "inverse-on-surface": "#f0f1f4"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "40px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-xl": "48px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"]
      },
      "fontSize": {
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
